import pptxgen from "pptxgenjs";

const COLORS = {
  primary: "2563EB",      // Blue 600
  secondary: "0F172A",    // Slate 900
  accent: "60A5FA",       // Blue 400
  text: "334155",         // Slate 700
  lightBlue: "F0F7FF",    // Soft tint
  lightSlate: "F8FAFC",   // Neutral tint
  border: "E2E8F0",       // Slate 200
  white: "FFFFFF",
  muted: "64748B",        // Slate 500
};

export const generatePpt = async (data) => {
  const ppt = new pptxgen();
  ppt.layout = "LAYOUT_WIDE"; // 13.33 x 7.5 inches
  ppt.author = "CortexAI";
  ppt.title = data.title;
  ppt.subject = data.title;
  ppt.company = "CortexAI";
  ppt.theme = {
    headFontFace: "Aptos",
    bodyFontFace: "Aptos",
    lang: "en-US",
  };

  addCover(ppt, data);

  data?.slides?.forEach((s, i) => {
    addContentSlide(ppt, s.title, s.points || [], i + 1, data.slides.length);
  });

  addThankYou(ppt);
  return ppt;
};

const addCover = (ppt, data) => {
  const slide = ppt.addSlide();
  slide.background = { color: COLORS.primary };

  // Decorative top border strip
  slide.addShape(ppt.ShapeType.rect, {
    x: 0,
    y: 0,
    w: 13.33,
    h: 0.2,
    fill: { color: COLORS.accent },
    line: { color: COLORS.accent },
  });

  // Slide Title
  slide.addText(data.title, {
    x: 1.0,
    y: 2.6,
    w: 11.33,
    h: 1.5,
    align: "center",
    valign: "middle",
    color: COLORS.white,
    bold: true,
    fontSize: 36,
    shrinkText: true,
  });

  // Subtitle / Generator tag
  slide.addText("Generated by CortexAI", {
    x: 1.0,
    y: 4.2,
    w: 11.33,
    h: 0.5,
    align: "center",
    color: "BFDBFE",
    fontSize: 14,
  });
};

const addContentSlide = (ppt, title, points, page, total) => {
  const slide = ppt.addSlide();
  slide.background = { color: COLORS.white };

  // Slide Header
  slide.addText(title, {
    x: 0.8,
    y: 0.4,
    w: 11.73,
    h: 0.6,
    fontSize: 24,
    bold: true,
    color: COLORS.primary,
  });

  slide.addShape(ppt.ShapeType.line, {
    x: 0.8,
    y: 1.05,
    w: 11.73,
    h: 0,
    line: { color: COLORS.border, width: 1.2 },
  });

  // Dynamic layout calculation for bullet points
  const count = Math.max(points.length, 1);
  const startY = 1.35;
  const availableHeight = 5.2; // space between divider and footer
  const rowGap = 0.16;
  const cardHeight = Math.min(
    0.72,
    (availableHeight - (count - 1) * rowGap) / count
  );

  points.forEach((point, i) => {
    const y = startY + i * (cardHeight + rowGap);

    // Card background
    slide.addShape(ppt.ShapeType.roundRect, {
      x: 0.8,
      y,
      w: 11.73,
      h: cardHeight,
      fill: { color: i % 2 ? COLORS.lightSlate : COLORS.lightBlue },
      line: { color: COLORS.border, width: 0.8 },
      radius: 0.06,
    });

    // Bullet icon indicator
    slide.addShape(ppt.ShapeType.ellipse, {
      x: 1.1,
      y: y + cardHeight / 2 - 0.05,
      w: 0.1,
      h: 0.1,
      fill: { color: COLORS.primary },
      line: { color: COLORS.primary },
    });

    // Content text
    slide.addText(point, {
      x: 1.35,
      y: y + 0.04,
      w: 11.0,
      h: cardHeight - 0.08,
      fontSize: 14,
      color: COLORS.text,
      valign: "middle",
      fit: "shrink",
      wrap: true,
    });
  });

  // Footer Branding
  slide.addText("CortexAI", {
    x: 0.8,
    y: 6.9,
    w: 3.0,
    h: 0.3,
    fontSize: 10,
    color: COLORS.muted,
  });

  // Footer Page Number
  slide.addText(`${page} / ${total}`, {
    x: 10.53,
    y: 6.9,
    w: 2.0,
    h: 0.3,
    align: "right",
    fontSize: 10,
    color: COLORS.muted,
  });
};

const addThankYou = (ppt) => {
  const slide = ppt.addSlide();
  slide.background = { color: COLORS.secondary };

  slide.addText("Thank You", {
    x: 0,
    y: 2.8,
    w: 13.33,
    h: 1.0,
    align: "center",
    valign: "middle",
    color: COLORS.white,
    fontSize: 36,
    bold: true,
  });

  slide.addText("Generated by CortexAI", {
    x: 0,
    y: 6.9,
    w: 13.33,
    h: 0.3,
    align: "center",
    color: "94A3B8",
    fontSize: 10,
  });
};